require: rubocop-rspec
inherit_gem:
  bixby: bixby_default.yml
AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3
  Exclude:
    - 'valkyrie/**/*'
Naming/FileName:
  Enabled: true
  Exclude:
    - 'Gemfile'
    - '**/*.rake'
    - 'valkyrie-cloud_search.gemspec'
Metrics/BlockLength:
  Exclude:
    - '**/*.gemspec'
    - 'spec/**/*'
    - 'lib/valkyrie/specs/**/*'
    - 'lib/specs/**/*'
    - 'lib/tasks/dev.rake'
RSpec/MultipleExpectations:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
